# Generated by Django 3.2.20 on 2023-09-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
