# Generated by Django 3.2.20 on 2023-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
