# Generated by Django 3.2.20 on 2023-09-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_taskstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStats',
        ),
    ]
